builds:
  - binary: netutil
    goos: 
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
- name: netutil
  homepage: https://github.com/asukiasyan/homebrew-tools 
  tap:
    owner: asukiasyan
    name: homebrew-tools
  commit_author:
    name: asukiasyan

checksum:
  name_template: 'checksums.txt'