repos:
  - repo: https://github.com/asukiasyan/netutil.git

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: <git sha or tag>
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [chore, docs, feat, fix, refactor, revert, test]